---
title: "final_proj1"
author: "hannah hess"
date: "November 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stargazer)
library(gtrendsR)
library(tidyverse)
```


```{r}
#showing/determining high volume porn searches 
```



```{r}


#I have a problem: the gtrends data set does not indicate the presence or absence of Ramadan. I have to pull that info from a different data set I have called ramadan_holiday
#My google trends data set (D1_interest) includes ramadan search values for a whole week 
#manipulate data set to add all days of the week 
D1_interest$date1 = as.Date(D1_interest$date) + 1 
D1_interest$date2 = as.Date(D1_interest$date) + 2 
D1_interest$date3 = as.Date(D1_interest$date) + 3 
D1_interest$date4 = as.Date(D1_interest$date) + 4 
D1_interest$date5 = as.Date(D1_interest$date) + 5 
D1_interest$date6 = as.Date(D1_interest$date) + 6 

D1_interest$year <- substring(D1_interest$date,1,4)


#For loop to create (1) a "days_in_ram" variable ->  the number of days in a given week with ramadan present and also (2) "in_ram" variable -> (0 or 1) whether or not ramadan is present in that week
#first iterate over a week in a given year in the D1_interests data set to see if there are any matches for Ramadan occuring
#count the number of days of a given week in teh D1_interest$date variable which overlap with ramadan
#create a binary variable to code 1 if a week includes more than 3 days of ramadan. 

for (i in 1:length(D1_interest$date)) {
  D1_interest[i, "days_in_ram"] = 0 
  for( j in c("date" , "date1", "date2" , "date3", "date4", "date5", "date6")){
    if ( (D1_interest[i, j] > ramadan_dates[ramadan_dates$year==   D1_interest[i, "year"]   &  ramadan_dates$Holiday == "Ramadan" , ]$start  ) & (D1_interest[i, j] < ramadan_dates[ramadan_dates$year== D1_interest[i,"year"] & ramadan_dates$Holiday == "Ramadan" ,]$end  ) ) {
        D1_interest[i, "days_in_ram"] =   D1_interest[i, "days_in_ram"]  + 1
    }
  }
  
  if (D1_interest[i, "days_in_ram"] > 2){
      D1_interest[i,"in_ram"] = 1
  } else{
      D1_interest[i,"in_ram"] = 0
  }
  
  
}

#Thank you to Eric Wasserman Harvard 2019 Dunster House for helping me conceptualize how best to approach the coding problem above!


#my next step in data manipulation before running a regression will be to add an additional variable for year so that I can control for that. 
#I also may go back up (before doing the ramadan stuff) and create a combined variable of porn searches called porn which is the average of the high volume porn searches I've found 



```








#create and merge large data set organized by year and dates and countries which show the occurence of ramadan 






Variable names:
country 
year 
Ramadan vs not ramadan 
search volume (porn/sex)





first - try to pull a cross country data frame from google 
```{r}

#create preliminary data set - last 5 years 
D1 <- gtrends(keyword = c("sex", "porn"), geo = c("EG", "SA"), time = "today+5-y")
D1_interest <- D1$interest_over_time %>% 
  mutate(data)

ramadan_dates

join()
#since I'm still figuring out how to join the dates - 
        
      

```


then - rearrange the countries 
```{r}
# I will make a graph by bringing togethor the countries and then 


D1 <- gtrends(keyword = c("sex", "porn"), geo = c("EG", "SA"), time = "today+5-y")


D1_interest <- D1$interest_over_time %>% 
  mutate(data)




```

