---
title: "testing google trends"
author: "hannah hess"
date: "November 28, 2018"
output: html_document
---

```{r setup, include=FALSE, cache= TRUE}
knitr::opts_chunk$set(echo = TRUE)


library(gtrendsR)
library(ggplot2)
library(lettercase)
library(viridis)
library(pals)
library(scico)
library(ggrepel)
library(tidyverse)
library(readxl)
```




```{r, include = FALSE, cache = TRUE}

#set nice theme for background of first plot 
my_theme <- function() {
    theme_bw() +
    theme(panel.background = element_blank()) +
    theme(plot.background = element_rect(fill = "seashell")) +
    theme(panel.border = element_blank()) +                     # facet border
    theme(strip.background = element_blank()) +                 # facet title background
    theme(plot.margin = unit(c(.5, .5, .5, .5), "cm")) +
    theme(panel.spacing = unit(3, "lines")) +
    theme(panel.grid.major = element_blank()) +
    theme(panel.grid.minor = element_blank()) +
    theme(legend.background = element_blank()) +
    theme(legend.key = element_blank()) +
    theme(legend.title = element_blank())
  }

```



```{r, warning = FALSE, message = FALSE, cache = TRUE}

#introductory plot to display pornography search data 
SA_data <- gtrends(c("sex","porn"), gprop = "web", geo = c("SA"))


plot(SA_data) + 
  my_theme() +
  geom_line(size = 0.5) 



#graph with hourly data on sex and porn searches - to get a sense of the evening hours when most sex/porn searches occur 

hourly <- gtrends(c("sex","porn"), gprop = "web", geo = c("SA"), time = "now 7-d") 

 hourly$interest_over_time %>% 
  mutate(day = lubridate::wday(date, label = TRUE), hour = lubridate::hour(date)) %>% 
    ggplot() +
  geom_line(aes(x = hour, y = hits, colour = keyword)) +
  geom_smooth(aes(x = hour, y = hits), se = FALSE) +
  facet_grid(. ~ day) +
  theme_bw() + 
  theme(legend.position = 'top') +
  scale_x_continuous(breaks = c(6, 12, 18, 24)) +
  labs(y = NULL, x = "Time of Day", 
       caption = "November 27, 2018 11:00am to December 4, 2018 1:00pm",
       colour = NULL, title = "Google Trends Popularity of 'porn' or 'sex' over a Week in Saudi Arabia")



 hourly2 <- gtrends(c("sex","porn"), gprop = "web", geo = c("JO"), time = "now 7-d") 

hourly2$interest_over_time %>% 
  mutate(day = lubridate::wday(date, label = TRUE), hour = lubridate::hour(date)) %>% 
    ggplot() +
  geom_line(aes(x = hour, y = hits, colour = keyword)) +
  geom_smooth(aes(x = hour, y = hits), se = FALSE) +
  facet_grid(. ~ day) +
  theme_bw() + 
  theme(legend.position = 'top') +
  scale_x_continuous(breaks = c(6, 12, 18, 24)) +
  labs(y = NULL, x = "Time of Day", 
       caption = "November 27, 2018 11:00am to December 4, 2018 1:00pm",
       colour = NULL, title = "Google Trends Popularity of 'porn' or 'sex' over a Week in Jordan")



```
```{r, cache = TRUE}
#graph with rectanglas for ramadan presence

#read in the first graph which includes indicators for the presence of ramadan/eid and the value for sex and porn searches
graph <- read_rds("D1_interest.rds") %>% 
select(-keyword, -date1, -date2, -date3, -date4, -date5, -date6) 


graph1 <- graph %>%
  mutate(hits = hits.porn,
         category = "porn") %>%
  select(hits, category, date, in_ram)

graph2 <- graph %>%
  mutate(hits = hits.sex,
         category = "sex") %>%
select(hits, category, date, in_ram)

graph3 <- bind_rows(graph1, graph2)


#read in data of ramadan dates

ramadan_dates <- read_excel("ramadan_dates.xlsx") %>% 
filter(year >= 2014)




```


```{r}


ggplot() + geom_line(data = graph3, aes(x = date, y = hits, colour = category))+ geom_rect(data= ramadan_dates, aes(xmin=start, xmax=end, ymin=-Inf, ymax=+Inf), alpha = 0.2)



```

```{r, cache= TRUE, warning = FALSE, message = FALSE}

yearly <- gtrends(c("sex","porn"), geo = c("SA", "JO"), time = "today+5-y")  
yearly = yearly$interest_over_time

ggplot() + geom_line(data = yearly, aes(x = date, y = hits, colour = keyword)) + 
  geom_rect(data = ramadan_dates, aes(xmin=start, xmax=end, ymin=-Inf, ymax=+Inf), alpha = 0.2)





```

